install:
  - choco install gitversion.portable -pre -y

configuration: Release

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  verbosity: normal

after_build:
  - cmd: ECHO nuget pack .\src\Unic.UrlMapper.Core\Unic.UrlMapper.Core.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack .\src\Unic.UrlMapper.Core\Unic.UrlMapper.Core.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Unic.UrlMapper.Core.%GitVersion_NuGetVersion%.nupkg"
