//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unic.UrlMapper.Website.sitecore_modules.Shell.Unic.UrlMapper {
    
    
    public partial class Import_Dialog_Frame {
    }
}
